### ISSUE TITLE
özelleştirme sorunu

### ISSUE THREAD

**Issue by nanoeray** [OgnitorenKs/Toolbox#1]
Neden performans ayarlarını (menü 11 - seçenek 1) uyguladıktan sonra cihaz yönetimim kısıtlandı/kuruluş hesabına geçti?

https://prnt.sc/1t3ZLjtFj8Q-

**Comment by OgnitorenKs** [comment]
Merhaba arka plan değiştirildiği için bu şekilde uyarı veriyor. Aşağıdaki
komutları yönetici yetkili CMD ekranında uyguladıktan sonra sistemi yeniden
başlatın.

reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
/v "Wallpaper" /f
reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
/v "WallpaperStyle" /f

Eray Tuğrul Gül ***@***.***>, 22 Mar 2024 Cum, 16:04
tarihinde şunu yazdı:

**Comment by nanoeray** [comment]
Teşekkürler. İşlem başarılı sadece /v komutunu tanımadı

**Comment by OgnitorenKs** [comment]
Github eksikliğinden kaynaklı bir sorun oluşmuş ilk mesajımı mail üzerinden yazdım muhtemelen bundan kaynaklandı. iki regedit silme komutu paylaştım ancak bunu 4 satır olarak aldığı için /v komutunu tanımamıştır. Doğrusu aşağıdaki gibi olacaktır. 

• reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v "Wallpaper" /f
• reg delete "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v "WallpaperStyle" /f

**Comment by nanoeray** [comment]
Merhaba, yanıtınız için teşekküler. Tespit ettiğim bir diğer sorun ise ctfmon /  input servisleri çalışmıyor. Buda windows terminal gibi uygulamalarda text girişi sağlayamamaya sebep oluyor ek olarak @ vb simgeler yapılamıyor klavyeden

**Comment by OgnitorenKs** [comment]
Matematik ifade tanıyıcısı kaldırılınca bu tarz sorunlara neden oluyor. @ tuşları gibi sorunları bugüne kadar gözlemlememiştim. Geri bildiriminiz için teşekkür ederim.

Toolbox'ın 4.2.4 güncellemesiyle playbook bölümünde artık bileşen silmeden güvenli işlem yollarını tercih ettim. Ayrıca Playbook kısmı için yeni güncellemeyle birlikte ana menüde yönlendirme bilgisi yer almayacak. Toolbox'ın 4.2.4 sürümünü yayınladığımda bu bölümü kullanmak için ana menüde "playbook" yazmanız gerekecek.

**Comment by nanoeray** [comment]
Yanıtınız için teşekkürler, terminal sorunlarını çözebildim ancak @ sorununu çözemedim, bununla ilgili yardımcı olabilir misiniz?

**Comment by OgnitorenKs** [comment]
Çözümünü net olarak bilmiyorum. Klavyenizden kaynaklı bir sorun değilse yaptığım araştırmalarda aşağıdaki regedit kaydını eklemeyi tavsiye etmişler. Kodu uygulamak için CMD'yi yönetici olarak çalışıtırp aşağıdaki kodu uygulayın.

reg add "HKCU\Control Panel\Input Method" /f /v "EnableHexNumpad" /t REG_SZ /d 1

Eğer eklenen bu komuttan dolayı farklı sorunlar yaşarsanız aşağıdaki komutu yine aynı şekilde yönetici yetkili CMD ekranına uygulayın.

reg delete "HKCU\Control Panel\Input Method" /v "EnableHexNumpad" /f
