### ISSUE TITLE
Playbook ayarları çok karışık

### ISSUE THREAD

**Issue by mikropsoft** [OgnitorenKs/Toolbox#6]
Merhaba, benimle ilgili bir sorun mu bilmiyorum ama, gerçekten playbook ayarlarının bulunduğu bölümde nasıl yapılandırılacağı hiç anlaşılmıyor. Örneğin, E,1,4,5,D,6,10,14 gibi bir sıralama verilmiş. Bu sıralamada anladığım kadarıyla, aç veya kapat butonundan sonra (A,E) girdiğimiz rakamlar, ayarların açılması ve kapanmasıyla ilgili işlevi yerine getiriyor. Ancak bu şekilde yapıldıktan sonra hangi ayarların yapıldığına dair basit bir gösterge göremiyorum. Unuttuğum sırada bu sıkıntı çıkarıyor ve menüye dönmek için de bir seçenek yok. Bu yöntemi denedim ancak nedense seçtiğim seçeneklerle alakası olmayan işlemler uygulamaya başladı. Bug olabilir mi?

**Comment by OgnitorenKs** [comment]
Merhaba, Playbook uygulanmadan önce bazı ayarları hızlı bir şekilde yönetme imkanı sağlaması için söylediğiniz bölümü oluşturdum. Yönetimi karmaşık değil. Ayarları açmak için 'E' kapatmak için 'D' tuşlamanız gerekiyor. Yani Enable/Disable baş harfelerini temsil eder. E,1,4,5,d,6,10,14 tuşladığınızda istediğiniz ayarları olduğu gibi düzenler. Ayrıca bu bölümde ayarlar açık mı kapalı mı gösterecek şekilde düzenlendi. Bu bölüm karmaşık geliyorsa 'Q' tuşlayıp kalıp dosyasını not defteri ile açıp düzenleyebilirsiniz. 

Kontrollerimi sağladığımda bir sorun gözlemlemedim. Kalıpta ayar aktifleştirilmediği sürece Playbook o ayarı uygulamaz. Varsayılan kalıp ve tüm ayarlar kapalı şekilde test ettim, bir sorun görünmüyor. Kalıpta değişiklik yaparken genel şablon ayarını bozarsanız playbook bölümü kalıptan veriyi doğru şekilde çekemez. Bu da soruna neden olur. Kalıp düzenlemesiyle alakalı detaylı bilgileri blog sayfamdan paylaştım.

https://ognitorenks.blogspot.com/2024/05/playbook-kalp-dosyas-nasl-hazrlanr.html

**Comment by mikropsoft** [comment]
Sağolasın kolay gelsin.
